### ISSUE TITLE
example project

### ISSUE THREAD

**Issue by jgardezi** [ubaniabalogun/serverless-package-python-functions#2]
Hi,

Can you please post an example project for it for your current proposed structure.

Kind regards,
Javed Gardezi

**Comment by ubaniabalogun** [comment]
@jgardezi I'll put one together and get back to you this week.

**Comment by jgardezi** [comment]
@ubaniabalogun thank you that will be cool.

**Comment by ubaniabalogun** [comment]
@jgardezi https://github.com/ubaniabalogun/serverless-package-python-functions-demo
