### ISSUE TITLE
When useDocker is set to true requirements files are not found

### ISSUE THREAD

**Issue by JFox** [ubaniabalogun/serverless-package-python-functions#21]
Whenever you set the useDocker option to true, the packaging process breaks as the requirementsPath used is the one in the local machine but not the one inside the container. This causes [this line](https://github.com/ubaniabalogun/serverless-package-python-functions/blob/master/index.js#L66) to skip the if but afterwards breaking inside the docker container with `[serverless-package-python-functions] Could not open requirements file: [Errno 2] No such file or directory: '_build/your-awesome-service/requirements.txt'`

**Comment by jmartinez-jobsity** [comment]
Is this being looked into?

**Comment by JFox** [comment]
Is this being looked into?

**Comment by ubaniabalogun** [comment]
Hey @jfox. 
Yup this is being looked into. I'm slowly making my way through the PRs on here. 

It would help if you included steps to recreate your findings and details about your OS, serverless version and plugin version. 
I think I wasn't able to recreate on my end when I took a look last weekend. 
Thanks

**Comment by JFox** [comment]
OS: Debian jessie
Serverless version: 1.24.0
Plugin version: 0.24.0
Docker Server Version 1.12.6 & Client Version 17.09.0-ce

```
Serverless: [serverless-package-python-functions] Packaging awesome-project...
 
  Serverless Error ---------------------------------------
 
  [serverless-package-python-functions] Could not open requirements file: [Errno 2] No such file or directory: '_build/awesome-project/requirements.txt'
```

**Comment by ubaniabalogun** [comment]
@JFox Thanks for the issue and the PR! Version 0.2.5 is now available. 🎉

**Comment by JFox** [comment]
@ubaniabalogun my pleasure to contribute. Thanks to you for the plugin!
