### ISSUE TITLE
Not working for lxml & psycopg2

### ISSUE THREAD

**Issue by nils2504** [ubaniabalogun/serverless-package-python-functions#28]
Hi there, 

there seems to be an issue when using it with lxml & psycopg2.
"invalid ELF header".
I mean the issue is known - normally that error occurs when using the local machine for getting those packages and not the AWS native AMI. But i thought that problem would be solved with the docker images of lambci?

Thanks
Nils

**Comment by ubaniabalogun** [comment]
Hi @nils2504,
That problem should be solved using the docker images. Can you share your serverless.yml and the version of the plugin you're using with me?
Thanks,

**Comment by nils2504** [comment]
Sorry - it was my fault - i forgett to add useDocker...
