### ISSUE TITLE
serverless-package-python-functions vs serverless-python-requirements?

### ISSUE THREAD

**Issue by braco** [ubaniabalogun/serverless-package-python-functions#36]
Hi, is this package better in any way than `serverless-python-requirements`?

> I don't think serverless-package-python-functions is necessary since this plugin gained the same functionality.

https://github.com/UnitedIncome/serverless-python-requirements/issues/106#issuecomment-388814729

**Comment by ubaniabalogun** [comment]
Hi @braco,
I wrote this plugin to enable per-function requirements when packaging python lambda functions. At the time I wrote the plugin, `serverless-python-requirements` did not support that feature (although, I believe support for that feature was added earlier this year)

I haven't compared & contrasted the feature set & implementation of both packages so can't say if one is better than the other. The most I can say is, at the time they were created, they served different use-cases.

**Comment by heri16** [comment]
It is always great to have alternatives. Was surprised to see we now have two python related plugins for serverless!

**Comment by aparkerlue** [comment]
`serverless-python-requirements` doesn't yet have a streamlined solution for including library code in multiple packages.

There is an open issue for this feature, the discussion around which includes a solution using the `vendor` property: https://github.com/UnitedIncome/serverless-python-requirements/issues/168.
