### ISSUE TITLE
Add support for compiled libraries using Docker

### ISSUE THREAD

**Issue by ubaniabalogun** [ubaniabalogun/serverless-package-python-functions#4]
# This is a Feature Proposal
## Description
Some Python libraries only work on the system they were compiled for. An example is numpy. These packages will work on the system they were installed and packaged on but will fail when deployed to AWS Lambda. 

Docker makes it possible to use the version of a package that works on AWS Lambda. This feature request is concerned with providing a plugin configuration that allows libraries to be packaged in a Docker container that replicates the AWS Lambda environment.

**Comment by marcoromelli** [comment]
Thanks @ubaniabalogun 
I think the solution is working, but there is a size problem with some dependencies. For example I tried to make a Lambda function with 'Tensorflow' and it's too big to be uploaded.
I know for sure that is possible to squeeze it to fit the Lambda limit but I'm not sure on the exact procedure.

**Comment by ubaniabalogun** [comment]
Hey @marcoromelli,
The 'Tensorflow size' problem is an interesting one. 
I'll have to research for a while about how to implement a solution for it that doesn't require modifying the way people handle their imports.
